"""empty message

Revision ID: 008be83155e8
Revises: 0f862a974860
Create Date: 2017-06-22 17:47:48.754777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008be83155e8'
down_revision = '0f862a974860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('carts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'carts', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='unique')
    op.alter_column('carts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('carts', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
