"""empty message

Revision ID: 04465a685bff
Revises: 819f88815e08
Create Date: 2017-06-22 11:43:56.755244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04465a685bff'
down_revision = '819f88815e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
