"""empty message

Revision ID: 0f862a974860
Revises: 04465a685bff
Create Date: 2017-06-22 12:13:29.929703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f862a974860'
down_revision = '04465a685bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_index('ix_products_name', table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
